<a href="https://colab.research.google.com/github/qilin512/supervision/blob/master/CalculatePI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 统计的方法计算PI

In [ ]:
import numpy as np

N = 0
M = 0

P = 100000

pi = 0
pi_old = 100
e = 0.000001

k = 0
while abs(pi - pi_old) > e:
    pi_old = pi
    for i in range(1, P):
        x = np.random.rand()
        y = np.random.rand()
        N = N + 1
        if (x - 0.5) * (x - 0.5) + (y - 0.5) * (y - 0.5) < 0.25 :
            M = M + 1
    pi = 4 * M / N
    k = k + 1
    print("The %d th round: pi = %f" % (k, pi))

In [4]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [5]:
!ls "/content/drive/My Drive/"
!pwd

 2005届计算机科学与技术专业校友花名册.gsheet  'Colab Notebooks'
/content


In [6]:
!/opt/bin/nvidia-smi

Fri Oct 23 14:59:44 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0    72W / 149W |    369MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [ ]:
import torch

X, W_xh = torch.randn(3, 1), torch.randn(1, 4)
H, W_hh = torch.randn(3, 4), torch.randn(4, 4)
torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

tensor([[ 3.5965,  2.6176, -0.9681, -0.6186],
        [-0.1507, -0.3659, -2.5355,  0.2021],
        [ 0.7153, -0.0678,  2.6344, -2.8102]])

In [ ]:
torch.matmul(torch.cat((X, H), dim=1), torch.cat((W_xh, W_hh), dim=0))

tensor([[ 3.5965,  2.6176, -0.9681, -0.6186],
        [-0.1507, -0.3659, -2.5355,  0.2021],
        [ 0.7153, -0.0678,  2.6344, -2.8102]])

In [ ]:
import torch
import numpy as np
from __future__ import print_function

a = torch.ones((2,), dtype=torch.int8)
b = torch.ones(2, dtype=torch.int8)
print(a)
print(a.dtype)
print(b)
print(b.dtype)
c = np.zeros([3,4], dtype=np.float32)
print(c)
d = torch.from_numpy(c)
c[0][0] = 5
print(d)
print(d.dtype)

tensor([1, 1], dtype=torch.int8)
torch.int8
tensor([1, 1], dtype=torch.int8)
torch.int8
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[5., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [ ]:
print(torch.cuda.is_available())
device = torch.device("cuda")      # a CUDA device object
x = torch.randn(1)
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)             # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.float64))     # ``.to`` can also change dtype together!

True
tensor([-0.2223], device='cuda:0')
tensor([-0.2223], dtype=torch.float64)


In [ ]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
x = torch.tensor(1.0, requires_grad=True)
y = 2 * x
print(y.grad_fn)
y.backward()
print(x.grad)

tensor(2.)


In [ ]:
import torch
import numpy as np
#from __future__ import print_function
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.size())
y = torch.unsqueeze(x, 0)
print(y)
print(y.size())
z = torch.unsqueeze(x, 1)
print(z)
print(z.size())

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [2]:
import torch
import torch.nn as nn

class LinearNet(nn.Module):
    def __init__(self,n_feature):
        super().__init__()
        self.linear = nn.Linear(n_feature,1)
    def forward(self, x):
        y = self.linear(x)
        return y

mynet = LinearNet(2).cuda()
print(mynet)

x = torch.Tensor([1, 2]).cuda()
# print(x)

y = mynet(x)
print(y)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
tensor([-1.6237], device='cuda:0', grad_fn=<AddBackward0>)
